let dados = [
    {
        nome: "Tales de Mileto",
        descricao: "(c. 624-546 a.C.): O primeiro filósofo a buscar explicações racionais para a natureza.",
        resumo: "Tales de Mileto, considerado um dos Sete Sábios da Grécia Antiga, é amplamente reconhecido como o primeiro filósofo da história ocidental. Vivendo por volta do século VI a.C., na cidade-estado de Mileto, na Jônia, Tales inaugurou uma nova forma de pensar sobre o mundo, marcada pela busca por explicações racionais para os fenômenos naturais. Em vez de recorrer a mitos e divindades para explicar a origem e a constituição do universo, Tales propôs uma explicação naturalista. Segundo ele, a água era o princípio de todas as coisas, o *arché* (ἀρχή) que unificava a diversidade da natureza. Essa escolha não era arbitrária, mas baseava-se em suas observações do mundo: a água é essencial para a vida, está presente em todas as coisas e assume diferentes formas (sólida, líquida e gasosa). As principais ideias de Tales de Mileto podem ser resumidas da seguinte forma: Monismo hídrico: A crença de que a água é o elemento fundamental de tudo o que existe. Explicação naturalista: A busca por explicações racionais para os fenômenos naturais, em oposição às explicações mitológicas. Cosmologia: A preocupação em compreender a origem e a ordem do universo. Tales de Mileto marcou um ponto de virada na história do pensamento humano ao questionar as explicações tradicionais e buscar respostas baseadas na razão e na observação da natureza. Seu trabalho inspirou gerações de filósofos e cientistas, e suas ideias continuam a ser estudadas e debatidas até os dias de hoje. Ao propor que a água era o princípio de todas as coisas, Tales não apenas estabeleceu uma nova forma de pensar sobre o mundo, mas também inaugurou a tradição filosófica ocidental.",
        link: "https://pt.wikipedia.org/wiki/Tales_de_Mileto",
        imagem: "assets/img/TalesdeMileto.jpg"
    },
    {
        nome: "Anaximandro",
        descricao: "(c. 610-546 a.C.): Propôs o ápeiron como princípio originário de todas as coisas.",
        resumo: "Anaximandro de Mileto, um dos mais importantes filósofos pré-socráticos, nasceu na cidade-estado de Mileto, na Jônia, por volta do século VI a.C. Discípulo de Tales, Anaximandro buscou aprofundar as investigações sobre a origem e a constituição do universo, propondo uma explicação mais abrangente e cosmológica do que a de seu mestre. Em contraponto à teoria de Tales, que defendia a água como o princípio de todas as coisas, Anaximandro introduziu o conceito de *ápeiron*. O *ápeiron* não era um elemento específico como a água, o fogo ou o ar, mas sim uma substância infinita, indeterminada e eterna, que seria a origem de todas as coisas existentes. Essa substância primordial, segundo Anaximandro, não possuía qualidades definidas e era a fonte de onde emergiam todos os opostos, como o quente e o frio, o úmido e o seco. A partir do *ápeiron*, Anaximandro desenvolveu uma cosmologia complexa, buscando explicar a origem e a evolução do universo. Ele postulou que os mundos surgiam e se destruíam em um ciclo eterno, e que a Terra, inicialmente esférica e flutuando livremente no espaço, era circundada por um anel de fogo que separava os mundos.  Além de suas contribuições para a filosofia natural, Anaximandro também se destacou em outras áreas do conhecimento. Ele foi um dos primeiros a elaborar um mapa do mundo conhecido, demonstrando um grande conhecimento de geografia. Além disso, Anaximandro realizou importantes observações astronômicas, contribuindo para o desenvolvimento da astronomia grega. A filosofia de Anaximandro representa um marco importante na história do pensamento ocidental. Ao propor o *ápeiron* como princípio originário, ele inaugurou uma nova forma de pensar sobre o universo, buscando explicações racionais e naturais para os fenômenos cósmicos. As ideias de Anaximandro influenciaram profundamente os filósofos que o sucederam, como Heráclito e Empédocles, e continuam a ser estudadas e debatidas até os dias de hoje.",
        link: "https://pt.wikipedia.org/wiki/Anaximandro",
        imagem: "assets/img/Anaximandro.jpg"
    },
    {
        nome: "Heráclito de Éfeso",
        descricao: "(c. 540-470 a.C.): Defendeu a ideia da constante mudança e da unidade dos opostos.",
        resumo: "Heráclito de Éfeso, filósofo pré-socrático grego, é reconhecido por sua visão radicalmente dinâmica e processual da realidade. Sua famosa frase 'panta rei' (tudo flui) encapsula a ideia central de sua filosofia: a constante mudança é a única característica imutável do universo.Para Heráclito, o fogo não era apenas um elemento material, mas sim o princípio ativo e dinâmico que permeia todas as coisas. O fogo, em sua visão, representa a energia primordial que impulsiona as transformações contínuas da natureza. Essa concepção do fogo como *arché* (princípio) está intimamente ligada à sua doutrina da unidade dos opostos. Heráclito acreditava que os opostos, como quente e frio, seco e úmido, não são entidades separadas, mas sim aspectos interdependentes de uma mesma realidade. A harmonia do universo, segundo ele, surge da tensão e da interação constante entre esses opostos. A filosofia de Heráclito é marcada por um estilo aforístico e enigmático, o que torna a interpretação de suas ideias um desafio. Seus fragmentos, transmitidos por gerações posteriores, são repletos de paradoxos e metáforas que convidam à reflexão profunda. A ideia de que a guerra é o pai de todas as coisas, por exemplo, expressa a visão heraclitiana de um universo em constante conflito e transformação. O pensamento de Heráclito exerceu uma profunda influência sobre a filosofia posterior. Seus conceitos de fluxo, mudança e unidade dos opostos foram retomados e desenvolvidos por filósofos como Platão e Hegel. A dialética hegeliana, por exemplo, que busca a verdade através da contradição e da superação de opostos, encontra suas raízes na filosofia heraclitiana. Heráclito é considerado um dos pais da dialética, método de raciocínio que busca a verdade através da confrontação de ideias opostas. Sua filosofia, marcada por um profundo senso de movimento e transformação, continua a inspirar pensadores e a desafiar nossas intuições sobre a natureza da realidade.",
        link: "https://pt.wikipedia.org/wiki/Her%C3%A1clito",
        imagem: "assets/img/HeráclitodeÉfeso.jpg"
    },
    {
        nome: "Pitágoras de Samos",
        descricao: "(c. 570-495 a.C.): Fundador do pitagorismo, relacionou números e harmonia cósmica.",
        resumo:  "Pitágoras de Samos, filósofo e matemático grego, é figura central na história do pensamento ocidental. Nascido na ilha de Samos, fundou uma escola em Crotona, na Magna Grécia, onde desenvolveu uma filosofia que buscava compreender a natureza do universo através dos números.Os pitagóricos acreditavam que os números eram a essência de todas as coisas, a chave para desvendar a ordem cósmica. Essa visão numérica permeava todos os aspectos de sua filosofia, desde a cosmologia até a ética. A harmonia das esferas celestes, por exemplo, era vista como uma expressão da ordem numérica perfeita. O famoso teorema de Pitágoras, que relaciona os lados de um triângulo retângulo, é apenas um exemplo da importância que os números tinham para essa escola.Além da matemática, a filosofia pitagórica abrangia diversos outros campos, como a música, a astronomia e a ética. A música, por exemplo, era vista como uma manifestação da harmonia cósmica, e a prática musical era fundamental para a formação dos pitagóricos. A ética pitagórica enfatizava a pureza da alma, a busca pela sabedoria e a importância da comunidade. A escola pitagórica era uma comunidade bastante fechada, com ritos iniciáticos e um código de conduta rigoroso.A influência do pitagorismo foi profunda e duradoura. As ideias pitagóricas sobre os números, a harmonia e a imortalidade da alma tiveram um impacto significativo no pensamento de Platão e de outros filósofos posteriores. A escola pitagórica também deixou um legado importante para a matemática, a música e a filosofia da ciência.",
        link: "https://pt.wikipedia.org/wiki/Pit%C3%A1goras",
        imagem: "assets/img/PitágorasdeSamos.jpg"
    },
    {
        nome: "Parmênides de Eléia",
        descricao: "(c. 515-440 a.C.): Defendeu a imutabilidade do ser e a impossibilidade do não-ser.",
        resumo:  "Parmênides de Eléia, filósofo pré-socrático grego, é considerado um dos pensadores mais influentes da antiguidade. Sua filosofia, centrada na questão do ser e do não-ser, revolucionou a maneira como os gregos concebiam a realidade. Em sua obra principal, 'Sobre a Natureza', Parmênides defende a ideia de que o ser é eterno, imutável e uno. O ser, segundo ele, não tem começo nem fim, não se move e não se transforma. O filósofo eleático contrapõe radicalmente o ser ao não-ser, argumentando que o não-ser é impensável e incognoscível. A partir dessa distinção fundamental, Parmênides desenvolve uma crítica ao mundo sensível, que percebemos pelos sentidos e que está em constante mudança. Para ele, o mundo sensível é uma ilusão, uma aparência enganosa que oculta a verdadeira natureza da realidade. O mundo verdadeiro, segundo Parmênides, é o mundo do ser, que é apreendido não pelos sentidos, mas pela razão. A razão, para o filósofo, é o único instrumento capaz de alcançar o conhecimento verdadeiro. A filosofia de Parmênides teve um profundo impacto no desenvolvimento da metafísica e da epistemologia. Seus argumentos sobre a imutabilidade do ser e a distinção entre o mundo sensível e o mundo inteligível foram retomados e desenvolvidos por filósofos posteriores, como Platão e Aristóteles. A escola eleática, fundada por Parmênides, teve um papel fundamental na história da filosofia. Os eleáticos, através de seus paradoxos e argumentos rigorosos, desafiaram as intuições comuns sobre o mundo e estimularam a reflexão filosófica sobre questões fundamentais, como a natureza da realidade, o conhecimento e a linguagem.",
        link: "https://pt.wikipedia.org/wiki/Parm%C3%AAnides#:~:text%C3%AAnides%ou%AAnides%20ou%C3%A9nides%%de%Eleia%escola%pitag%C3%B3rica% especialmente%20com%2Ameinias.",
        imagem: "assets/img/ParmênidesdeEléia.jpg"
    },
    {
        nome: "Sócrates",
        descricao: "(c. 470-399 a.C.): Conhecido por seu método maiêutico e por suas reflexões sobre a ética e a política.",
        resumo: "Sócrates, filósofo ateniense, é considerado um marco fundamental na história da filosofia ocidental. Embora não tenha deixado nenhum texto escrito, sua figura e seu pensamento foram amplamente divulgados por seus discípulos, principalmente Platão.O método socrático, conhecido como maiêutica, é uma das maiores contribuições de Sócrates para a filosofia. Através de diálogos e perguntas incisivas, Sócrates buscava levar seus interlocutores a reconhecer a própria ignorância e a buscar a verdade por meio da razão. A maiêutica, comparada ao parto pela própria mãe de Sócrates, era um processo de “parir” ideias e conceitos.A ética socrática gira em torno da busca pela virtude e pelo bem. Para Sócrates, o conhecimento do bem é condição necessária para a ação virtuosa. A famosa máxima 'conhece-te a ti mesmo' resume a importância da autoconhecimento na busca pela felicidade. A coragem de Sócrates em defender suas ideias, mesmo diante da condenação à morte por envenenamento, tornou-o um símbolo da busca pela verdade e da integridade moral.A política também era um tema central na filosofia de Sócrates. Ele acreditava que a verdadeira justiça só poderia ser alcançada por meio da virtude dos cidadãos. Sócrates criticou a democracia ateniense, argumentando que a maioria nem sempre escolhe o que é melhor para a cidade.A filosofia de Sócrates exerceu uma profunda influência sobre o pensamento ocidental. Seus discípulos, como Platão e Aristóteles, desenvolveram e aprofundaram suas ideias, dando origem a diversas escolas filosóficas. A ênfase de Sócrates na importância da razão, da virtude e do diálogo continua a inspirar filósofos e pensadores até os dias de hoje.",
        link: "https://pt.wikipedia.org/wiki/S%C3%B3crates",
        imagem: "assets/img/Sócrates.jpg"
    },
    {
        nome: "Platão",
        descricao: "(c. 428-348 a.C.): Discípulo de Sócrates, desenvolveu a teoria das Formas e fundou a Academia.",
        resumo: "Platão, filósofo ateniense e discípulo de Sócrates, é uma das figuras mais influentes da história da filosofia. Sua obra, marcada por uma profunda reflexão sobre a natureza da realidade, da ética e da política, moldou o pensamento ocidental por mais de dois mil anos.Uma das ideias mais conhecidas de Platão é a teoria das Formas, também conhecida como teoria das Ideias. Segundo essa teoria, o mundo sensível que percebemos pelos nossos sentidos é apenas uma cópia imperfeita de um mundo superior de Formas perfeitas e imutáveis. As Formas são os modelos originais de todas as coisas existentes no mundo sensível. Por exemplo, a Forma do Belo é o modelo perfeito de beleza, e todos os objetos belos que vemos no mundo são apenas participações imperfeitas dessa Forma.Platão fundou a Academia, a primeira instituição de ensino superior do mundo ocidental. Nela, ele reuniu seus discípulos para discutir filosofia, matemática e outras disciplinas. A Academia se tornou um centro intelectual de grande importância e influenciou o pensamento filosófico por séculos.A obra mais famosa de Platão é 'A República', um diálogo em que o filósofo apresenta sua visão ideal de uma sociedade justa e bem governada. Nessa obra, Platão defende a ideia de que os filósofos, por possuírem conhecimento das Formas, são os mais aptos a governar.As ideias de Platão sobre a alma, a imortalidade, a justiça, a educação e a política continuam a ser objeto de estudo e debate até os dias de hoje. Sua filosofia exerceu uma profunda influência sobre o pensamento medieval e renascentista, e suas ideias sobre a natureza da realidade e do conhecimento ainda são relevantes para a filosofia contemporânea.",
        link: "https://pt.wikipedia.org/wiki/Plat%C3%A3o",
        imagem: "assets/img/Platão.jpg"
    },
    {
        nome: "Aristóteles",
        descricao: "(384-322 a.C.): Discípulo de Platão, abrangeu diversas áreas do conhecimento e fundou o Liceu.",
        resumo: "Aristóteles, filósofo grego nascido em Estagira, Macedônia, é considerado um dos maiores pensadores da Antiguidade. Discípulo de Platão, fundou o Liceu em Atenas, uma escola onde lecionou e conduziu pesquisas em diversas áreas do conhecimento. Sua obra abrangente e sistemática influenciou profundamente o pensamento ocidental por séculos. Aristóteles desenvolveu uma filosofia realista e empírica, em contraste com o idealismo de Platão. Para ele, a realidade é composta por substâncias individuais e concretas, que possuem propriedades ou acidentes. A substância é o que faz uma coisa ser o que ela é, enquanto os acidentes são as características que podem mudar sem alterar a natureza essencial da coisa.  Uma das maiores contribuições de Aristóteles foi a teoria das quatro causas, que busca explicar a realidade através de quatro aspectos: a causa material (o que algo é feito), a causa formal (a forma ou estrutura), a causa eficiente (o agente que produz algo) e a causa final (o fim ou propósito para o qual algo existe). Essa teoria influenciou profundamente a ciência e a filosofia natural por séculos. Aristóteles também desenvolveu uma ética da virtude, na qual a felicidade é o objetivo final da vida humana. A virtude, para ele, é o meio-termo entre dois extremos, e se adquire através do hábito e da prática. Sua política, por sua vez, buscava encontrar a melhor forma de governo para garantir a felicidade dos cidadãos. A obra de Aristóteles abrangeu praticamente todas as áreas do conhecimento da época, incluindo lógica, metafísica, física, biologia, psicologia, ética, política, retórica e poética. Sua influência se estendeu por toda a Idade Média e Renascimento, e seus escritos continuam a ser estudados e debatidos até os dias de hoje.",
        link: "https://pt.wikipedia.org/wiki/Arist%C3%B3teles",
        imagem: "assets/img/Aristóteles.jpg"
    },
    {
        nome: "Epicuro",
        descricao: "(c. 341-270 a.C.): Fundador do epicurismo, defendia o prazer como bem supremo.",
        resumo: "Epicuro de Samos foi um filósofo grego que fundou o epicurismo, uma das escolas filosóficas mais influentes da Antiguidade. Sua filosofia, centrada na busca pelo prazer, oferece um guia para uma vida feliz e serena. Para Epicuro, o prazer não se limita aos prazeres sensuais, mas abrange também a ausência de dor e a tranquilidade da alma, que ele denominava *ataraxia*. A felicidade, segundo o filósofo, não reside na busca por prazeres intensos e passageiros, mas sim na obtenção de um estado de prazer moderado e duradouro. A *aponia*, ou seja, a ausência de dor física e mental, era considerada fundamental para alcançar a ataraxia. O epicurismo propõe uma vida simples, livre de excessos e preocupações com bens materiais. A amizade, a sabedoria e a contemplação da natureza eram valorizadas como fontes de prazer duradouro. A filosofia epicurista também defendia a ideia de que os deuses não se interessam pela vida humana e, portanto, não há motivos para temer os deuses ou a morte. O epicurismo influenciou profundamente o pensamento filosófico e a cultura popular. A ideia de que o prazer é um bem legítimo e que a felicidade pode ser alcançada através da sabedoria e da moderação continua a ressoar até os dias de hoje. No entanto, o epicurismo foi frequentemente mal interpretado, sendo associado ao hedonismo extremo e ao individualismo. A filosofia de Epicuro oferece uma alternativa às visões mais pessimistas sobre a vida humana, propondo uma ética baseada na busca pela felicidade e na tranquilidade da alma.",
        link: "https://pt.wikipedia.org/wiki/Epicuro",
        imagem: "assets/img/Epicuro.jpg"
    },
    {
        nome: "Santo Agostinho",
        descricao: "(354-430): Um dos principais pensadores da Patrística, conciliou fé e razão.",
        resumo: "Santo Agostinho de Hipona, um dos mais influentes teólogos e filósofos da Patrística, marcou profundamente a história do pensamento ocidental. Sua jornada espiritual, desde uma juventude marcada pela busca por prazeres e conhecimento até sua conversão ao cristianismo, é narrada de forma profunda e íntima em suas 'Confissões', uma obra que se tornou um clássico da literatura universal. Agostinho é reconhecido por sua habilidade em conciliar a fé cristã com a filosofia grega, especialmente o platonismo. Ele desenvolveu uma filosofia cristã original, explorando temas como a natureza do mal, a graça divina, a livre vontade e a predestinação. A doutrina do pecado original, que afirma que todos os seres humanos nascem com uma inclinação para o pecado devido ao pecado de Adão, é uma de suas contribuições mais importantes para a teologia cristã. A filosofia de Agostinho também se debruçou sobre a questão da relação entre a fé e a razão. Para ele, a fé e a razão não são opostas, mas complementares. A fé precede a razão, mas a razão serve para aprofundar a compreensão da fé. Agostinho argumenta que a verdade revelada por Deus é superior à razão humana, mas que a razão pode ser utilizada para defender e explicar a fé. O pensamento de Agostinho exerceu uma profunda influência sobre a teologia medieval e continua a ser relevante para a filosofia e a teologia contemporâneas. Sua obra abrange uma ampla gama de temas, desde a filosofia da religião até a ética e a política. Agostinho é considerado um dos pais da filosofia medieval e um dos maiores pensadores da Igreja Católica.",
        link: "https://pt.wikipedia.org/wiki/Agostinho_de_Hipona",
        imagem: "assets/img/SantoAgostinho.jpg"
    },
    {
        nome: "Tomás de Aquino",
        descricao: "(1225-1274): A figura mais importante da escolástica, harmonizou fé e razão.",
        resumo: "Tomás de Aquino, monge dominicano italiano, é considerado o maior representante da Escolástica, corrente filosófica medieval que buscava conciliar a fé cristã com a razão filosófica. Conhecido como o 'Doutor Angélico', Aquino dedicou sua vida a construir um sistema filosófico abrangente, que unisse a teologia cristã com a filosofia aristotélica. Uma de suas maiores contribuições foi a demonstração da existência de Deus através de cinco vias. Essas vias, baseadas na observação da realidade, buscavam provar a existência de um ser primeiro, imutável e perfeito, que é a causa primeira de todas as coisas. Aquino também desenvolveu uma teoria da lei natural, segundo a qual a lei divina se manifesta na natureza humana, dando origem a uma lei moral universal, inscrita no coração de todo homem. A lei natural, portanto, orienta a conduta humana e serve como fundamento para a lei positiva, ou seja, as leis criadas pelos homens. A ética de Aquino é fundamentada na busca pela felicidade, que é identificada com a visão beatífica, ou seja, a contemplação de Deus. A virtude, para Aquino, é o meio termo entre dois vícios, e a graça divina é necessária para alcançar a perfeição moral. A obra de Tomás de Aquino, especialmente a 'Suma Teológica', é considerada uma das maiores sínteses do pensamento medieval. Suas ideias sobre a natureza de Deus, do homem e do universo influenciaram profundamente a teologia católica e a filosofia ocidental, e continuam a ser estudadas e debatidas até os dias de hoje.",
        link: "https://pt.wikipedia.org/wiki/Tom%C3%A1s_de_Aquino",
        imagem: "assets/img/TomásdeAquino.jpg"
    },
    {
        nome: "René Descartes",
        descricao: "(1596-1650): Pai da filosofia moderna, defendia o método da dúvida metódica.",
        resumo: "René Descartes, filósofo e matemático francês, é considerado o pai da filosofia moderna. Sua busca por um conhecimento fundamentado e indubitável o levou a desenvolver o método da dúvida metódica, uma forma de investigação que consiste em duvidar de tudo o que possa ser posto em dúvida. A partir dessa dúvida radical, Descartes chegou à sua famosa afirmação: 'Penso, logo existo'. Essa frase expressa a certeza indubitável de sua própria existência, pois o ato de duvidar é, em si mesmo, uma prova de que se está pensando. Essa afirmação se tornou um ponto de partida para a construção de um sistema filosófico racionalista. Descartes propôs um dualismo mente-corpo, segundo o qual a mente (ou alma) é uma substância pensante, enquanto o corpo é uma máquina extensa. A mente e o corpo são, portanto, duas realidades distintas, embora interagem entre si. Essa distinção marcou profundamente a filosofia e a ciência modernas. As ideias de Descartes tiveram um impacto significativo na filosofia, na ciência e na cultura ocidental. Seu método da dúvida metódica influenciou o desenvolvimento do pensamento científico, e seu dualismo mente-corpo gerou debates que perduram até hoje. A ênfase de Descartes na razão e na clareza metodológica contribuiu para o surgimento da filosofia moderna e para a construção de um conhecimento fundamentado.",
        link: "https://pt.wikipedia.org/wiki/Ren%C3%A9_Descartes",
        imagem: "assets/img/RenéDescartes.jpg"
    },
    {
        nome: "Baruch Spinoza",
        descricao: "(1632-1677): Filósofo racionalista, desenvolveu uma ética baseada na ideia de uma única substância.",
        resumo: "Baruch Spinoza, filósofo racionalista holandês, apresentou uma visão singular e controversa sobre o mundo e a natureza humana. Sua filosofia, exposta principalmente em sua obra 'Ética', gira em torno da ideia de uma única substância infinita e imutável, que ele identifica com Deus ou a Natureza. Tudo o que existe, segundo Spinoza, é uma modalidade ou atributo dessa substância única. A mente e o corpo, por exemplo, são apenas dois atributos diferentes da mesma substância. Essa visão monista, que unifica Deus e a natureza, desafiava as concepções religiosas e filosóficas de sua época. A ética de Spinoza é baseada na compreensão da natureza e do lugar do ser humano dentro dela. A felicidade, para ele, consiste em viver de acordo com a própria natureza racional, buscando a compreensão da ordem natural e a aceitação das coisas como elas são. A paixão, por outro lado, é vista como uma perturbação da razão e um obstáculo à felicidade. A filosofia de Spinoza influenciou profundamente o pensamento filosófico e teológico. Suas ideias sobre a natureza de Deus, a liberdade humana e a ética foram debatidas e desenvolvidas por filósofos posteriores, como Leibniz e Nietzsche. O panteísmo spinozista, a identificação de Deus com a natureza, continua a ser um tema central na filosofia e na teologia.",
        link: "https://pt.wikipedia.org/wiki/Baruch_Espinoza",
        imagem: "assets/img/BaruchSpinoza.jpg"
    },
    {
        nome: "John Locke",
        descricao: "(1632-1704): Um dos principais filósofos do empirismo, defendia que todo conhecimento deriva da experiência.",
        resumo: "John Locke foi um filósofo inglês do século XVII, considerado um dos fundadores do empirismo. Sua filosofia se baseia na ideia de que todo o conhecimento humano origina-se da experiência sensorial. Locke defendia que a mente humana ao nascer é como uma 'tábula rasa', uma folha em branco, e que todas as nossas ideias são formadas a partir das impressões que recebemos do mundo exterior através dos sentidos. Uma das suas contribuições mais importantes foi a teoria dos direitos naturais, na qual afirma que todos os seres humanos nascem com direitos inalienáveis, como o direito à vida, à liberdade e à propriedade. Essa teoria teve um profundo impacto no desenvolvimento das ideias liberais e democráticas, influenciando filósofos como Voltaire e Rousseau, e inspirando as revoluções liberais do século XVIII. Locke também desenvolveu uma teoria do conhecimento que distingue entre qualidades primárias (inerentes aos objetos, como a extensão e a forma) e qualidades secundárias (dependentes do sujeito que percebe, como a cor e o som). Suas ideias sobre a tolerância religiosa e a importância do governo limitado também tiveram grande influência no pensamento político.",
        link: "https://en.wikipedia.org/wiki/John_Locke",
        imagem: "assets/img/JohnLocke.jpg"
    },
    {
        nome: "Immanuel Kant",
        descricao: "(1724-1804): Figura central do idealismo alemão, revolucionou a filosofia com sua distinção entre fenômeno e noumeno.",
        resumo: "Immanuel Kant, filósofo alemão do século XVIII, é considerado um dos pensadores mais importantes da filosofia moderna. Sua obra, marcada pela busca por uma síntese entre o racionalismo e o empirismo, revolucionou a forma como entendemos o conhecimento e a realidade. Kant introduziu a distinção entre fenômeno (o mundo como aparece para nós, moldado pelas nossas faculdades cognitivas) e noumeno (a coisa em si, o mundo tal como ele é independentemente de nossa percepção). Ele também desenvolveu a teoria do conhecimento a priori, segundo a qual a mente humana possui categorias e estruturas que moldam nossa experiência do mundo, como as categorias de espaço, tempo e causalidade. A ética kantiana, por sua vez, é baseada no imperativo categórico, um princípio moral universal que nos obriga a agir de acordo com máximas que possamos querer que se tornem leis universais. As ideias de Kant tiveram uma profunda influência em diversas áreas do conhecimento, como a filosofia, a ciência e a ética, e continuam a ser objeto de estudo e debate até os dias de hoje.",
        link: "https://pt.wikipedia.org/wiki/Immanuel_Kant",
        imagem: "assets/img/ImmanuelKant.jpg"
    },
    {
        nome: "Friedrich Nietzsche",
        descricao: "(1844-1900): Filósofo niilista, Nietzsche criticou os valores tradicionais da cultura ocidental e defendia a superação do homem.",
        resumo: "Friedrich Nietzsche foi um filósofo alemão do século XIX, conhecido por sua crítica radical aos valores tradicionais da cultura ocidental. Em suas obras, Nietzsche questiona a existência de Deus, a moralidade cristã e os ideais de razão e progresso. Ele propõe uma nova ética, baseada na afirmação da vida e na superação do homem, que ele chama de Übermensch. Nietzsche defende que o indivíduo deve criar seus próprios valores e superar a moralidade tradicional, que considera decadente e escravizadora. O filósofo também é conhecido por suas ideias sobre a vontade de poder, que ele vê como a força motriz por trás de todos os fenômenos. A filosofia de Nietzsche é marcada por um estilo aforístico e por uma linguagem poética, o que a torna complexa e aberta a múltiplas interpretações. Suas ideias tiveram uma profunda influência em diversas áreas do pensamento, como a filosofia, a literatura, a psicologia e a política.",
        link: "https://pt.wikipedia.org/wiki/Friedrich_Nietzsche",
        imagem: "assets/img/FriedrichNietzsche.jpg"
    },
];